spring.application.name=Pay flow API
# PostgreSQL database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/payflowdb
spring.datasource.username=postgres
spring.datasource.password=123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

